language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - BASEDIR=$(pwd)
  - echo BASEDIR ${BASEDIR}
  - mkdir soft
  - cd soft
  - CLANG_VERSION=3.8.0
  - wget http://llvm.org/releases/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - tar -xf clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - ls
  - export CLANG_HOME=${PWD}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin
  - cd ${BASEDIR}
  - mkdir build
  - cd build
  - echo CLANG_HOME ${CLANG_HOME}
  - cmake .. -DCLANG_HOME=${CLANG_HOME} -DBUILD_TESTS=ON
  - make -j 8
  - make install

script:
  - cd ${BASEDIR}/build
  - # ./cocl_unittests
  - mkdir /tmp/foo
  - cd /tmp/foo
  - cp ${BASEDIR}/test/cocl/cuda_sample.cu .
  - CLANG_HOME=${CLANG_HOME} SETX=1 cocl cuda_sample.cu
  - ./cuda_sample

notifications:
  email:
    on_success: change
    on_failure: always
